apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: deadlettertopics
  namespace: default
spec:
  pubsubname: pubsub
  topic: poisonMessages
  route: /failedMessages
scopes:
  - pubsubrouting-service