apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: mysubscriptions
  namespace: default
spec:
  pubsubname: pubsub
  topic: inventory
  deadLetterTopic: poisonMessages  
  routes:
    rules:
      - match: event.type == "Widget"
        path: /inventory/widgets
      - match: event.type == "Gadget"
        path: /inventory/gadgets
    default: /inventory/products
scopes:
  - pubsubrouting-service